### ISSUE TITLE
[setgrid] Set Grid Quest

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen-cache#99]
One of the core data types in carmen-cache is a grid - a record of a particular location feature (e.g. New York City or Amsterdam) that includes its x,y coordinates and its feature ID. For some time we've packed these properties into 64 bits for efficient storage, but to make this work we've made various tradeoffs. One tradeoff is that we've had to truncate feature IDs to fit with all the other data within 64 bits. This makes looking up a feature from a grid quite challenging because the truncated feature ID may no longer be unique within a dataset.

For your sprint project we'll refactor a specific part of the carmen-cache API to prepare for a more flexible storage format in the future. We'll focus on the core get/set storage functions in carmen-cache.

------

### What is a grid?

A grid represents a geographic area (x, y) covered by a single feature (id) with information corresponding to how relevant and important it might be to a certain textual query (relev, score).

In JavaScript, we work with grids in the carmen codebase as objects, e.g.

```js
var grid = {
  x: 3,
  y: 17,
  relev: 1.0,
  score: 5,
  id: 15
};
```

This would be a valid grid object.

------

### Encoding grids as numbers

To store grids efficiently we have a little recipe for converting the grid object into a single number value and back:

> Grids are encoded as 53-bit integers (largest possible JS integer) storing the following information:
>
> info | bits | description
> ---- |------|------------
> x    | 14   | x tile cover coordinate, up to z14
> y    | 14   | y tile cover coordinate, up to z14
> relev| 2    | relev between 0.4 and 1.0 (possible values: 0.4, 0.6, 0.8, 1.0)
> score| 3    | score scaled to a value between 0-7
> id   | 20   | feature id, truncated to 20 bits

_From https://github.com/mapbox/carmen/blob/master/README.md#grid_

The idea of storing multiple properties in a single number is an encoding technique that is often used for optimization purposes. A simple example of this concept: suppose you've surveyed a bunch of people on their age and also whether they are happy about getting older. You might have two fields as a result:

name | age | happy_about_it
-----|-----|---------------
Jane | 31  | n
John |  7  | y
Joan | 91  | y
Jeff | 45  | n

A human-friendly formula to encode these two values into a single number might be:

1. Multiply age by 10
2. If the person is happy about their age, add 1

You would then end up with a single value that captures both pieces of information (if you know the recipe):

name | age_and_happy_about_it
-----|-----
Jane | 310
John |  71
Joan | 911
Jeff | 450

From a computer's perspective this recipe is pretty inefficient though - you'll never end up using digits 2-9 in the ones column. Since `happy_about_it` is a boolean (only two possible values), you might use a recipe more oriented toward binary like:

1. Multiply age by 2
2. If the person is happy about their age, add 1

name | age_and_happy_about_it
-----|-----
Jane | 62
John | 15
Joan | 183
Jeff | 90

Harder to read as a human but just as easy to reverse as a computer.

------

### Our current `_set()` API

Our current carmen cache set API works like this:

```js
var carmenCache = require('carmen-cache');
var grids = new carmenCache.MemoryCache('grids');

var a = 7036891598684201;
var b = 4785263596273714;
var c = 7036994682093628;

grids._set('paris', [a,b,c]);
```

It expects you to pass an array of numbers, where you've done the hard work of converting your grids to numbers. Because of this API design, it also means that changing how we store this data isn't a decision `carmen-cache` can make alone - we'd need to update all the code that calls `_set()` as well.

------

### Goal: let `_set()` do the encoding

The goal of this sprint is to get to the point where `_set()` can optionally accept an array of grid objects as well and do the conversion internally itself. So our new API will look like:

```js
var carmenCache = require('carmen-cache');
var grids = new carmenCache.MemoryCache('grids');

var a = { x: 3, y: 17, relev: 1.0, score: 5, id: 15 };
var b = { x: 4, y: 16, relev: 0.8, score: 3, id: 16 };
var c = { x: 3, y: 10, relev: 0.6, score: 2, id: 17 };

grids._set('paris', [a,b,c]);
```

And it will be up to `_set()` to do the appropriate conversion to how it wants to store the data. For now we'll use the exact same storage strategy (converting to a single number) but this API change will give us room in the future to experiment with more flexible ways of storing the data seamlessly.

------

### Backlog

For each item you’ll create a new branch that you’ll turn into a pull request.

- [x] https://github.com/mapbox/carmen-cache/issues/100 - Add tests for `_set()` where the data passed is an array of objects with grid properties instead of integers.
  - **Language:** JavaScript
  - **Goal:** sketch out the new `_set()` API from the JS side
- [x] https://github.com/mapbox/carmen-cache/issues/101 - Add an `encodeGrid()` cpp method and expose it to the JS API for testing
  - **Language:** C++
  - **Goal:** port the `grid.encode()` JS method so that `_set()` can convert grid properties to integers in cpp
- [x] https://github.com/mapbox/carmen-cache/issues/103 - Adjust `_set()` to be able to handle JS object input and convert those objects to integers
  - **Language:** C++
  - **Goal:** wire it all together and get tests passing

cc @fredngeorge

**Comment by fredngeorge** [comment]
#100, #101, and #103 merged.
